#  ██████╗ ██╗ ██████╗ ██████╗ ███╗   ███╗
#  ██╔══██╗██║██╔════╝██╔═══██╗████╗ ████║	Miquelo
#  ██████╔╝██║██║     ██║   ██║██╔████╔██║	https://github.com/MikyVlc/dotfiles
#  ██╔═══╝ ██║██║     ██║   ██║██║╚██╔╝██║	mar 16 jun 2026 18:05:08 CEST
#  ██║     ██║╚██████╗╚██████╔╝██║ ╚═╝ ██║
#  ╚═╝     ╚═╝ ╚═════╝ ╚═════╝ ╚═╝     ╚═╝


## ----- Shadows ----- ##

shadow = true;

shadow-radius = 12;
# shadow-opacity = .6
shadow-offset-x = -9;
shadow-offset-y = -9;
shadow-color = "#000000"

## ----- Fading ----- ##

fading = true;

fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;
no-fading-openclose = false;
no-fading-destroyed-argb = false;

## ----- Transparency ----- ##

frame-opacity = 1.0;

# inactive-dim-fixed = true

## ----- Corners ----- ##

corner-radius = 6;

## ----- Blur ----- ##

blur-method = "dual_kawase";
blur-size = 13;

blur-strength = 3;
blur-background = true;
blur-background-frame = true;
# blur-background-fixed = false

blur-kern = "3x3box";

#################################
#       General Settings        #
#################################

# Available backends "xrender" "glx" "egl"
backend = "egl"

dithered-present = false;
vsync = false;

detect-rounded-corners = false;
detect-client-opacity = true;
detect-transient = true;

use-damage = true;
# xrender-sync-fence = false
# transparent-clipping = false

#################################
#             Rules             #
#################################

rules: (

	{
		fade = false;
	},

	{
		match = "window_type = 'normal'";
		fade = true;	#-fade-switch
		shadow = true;	#-shadow-switch
	},

	{
		match = "window_type = 'dialog'";
		shadow = true;	#-shadow-switch
	},

	{
		match = "window_type = 'tooltip'";
		corner-radius = 0;
		opacity = 0.90;
	},
	
	{
		match = "fullscreen";
		corner-radius = 0;
	},

#	{
#		match = "window_type = 'dock'";
#		corner-radius = 0;
#		fade = true;
#	},

#	{
#		match = "window_type = 'dropdown_menu' || window_type = 'menu' || window_type = 'popup' || window_type = 'popup_menu'";
#		corner-radius = 0;
#	},

	{
        # Fix shadow related bugs on small UI elements
        match = "window_type = 'menu' || role = 'popup' || role = 'bubble'";
        shadow = false;
	},
    
	{
    	# Background blur excluded in xfce4-screenshooter
		match = "name = 'xfce4-screenshooter' &&"
		"class_g = 'Xfce4-screenshooter' &&"
		"window_type = 'dialog' &&
		!(
        _NET_WM_ALLOWED_ACTIONS ||
        _NET_WM_STATE ||
        _NET_WM_DESKTOP
		)";
		blur-background = false;
	},
	
	{
		match = "class_g = 'bspwm-scratch' || class_g = 'Updating'";
		opacity = 0.93;
		blur-background = false;	#-blur-switch
	},
	
	{
		match = "class_g = 'Polybar'	|| "
				"class_g = 'eww-bar'	|| "
				"class_g = 'Viewnior'	|| "
				"class_g = 'Rofi'		|| "
				"class_g = 'mpv'		|| "
				"class_g = 'bspwm-scratch'	|| "
				"class_g = 'Dunst'		|| "
				"class_g = 'retroarch'";
		corner-radius = 0;
	},
	
	{
		match = "name = 'Notification'		|| "
				"class_g ?= 'Notify-osd'    || "
				"class_g = 'Dunst'			|| "
				"class_g = 'Polybar'		|| "
				"class_g = 'Eww'			|| "
				"class_g = 'Xfce4-notifyd'			|| "
				"class_g = 'bspwm-scratch'	|| "
				"class_g = 'com.github.th_ch.youtube_music'		|| "
				"class_g = 'retroarch'		|| "
				"class_g = 'firefox'		|| "
				"class_g = 'Rofi'			|| "
				"class_g = 'Screenkey'		|| "
				"class_g = 'mpv'			|| "
				"class_g = 'Viewnior'		|| "
				"_GTK_FRAME_EXTENTS@";
		shadow = false;
	},

@include "picom-animations.conf"

)
